src/com/gh/model/Booking.java

Github - #4 
JIRA - GHS-7
###Todo
###ETC
- LocalDate 사용 했으니 사용법 참고 부탁드려요!!
- 메소드로 뺏던 예약 날짜 계산하는 로직 이 Booking 클래스에서 간단하게 구현했습니다!!
간단한 Booking vo 클래스에서 하는게 좋다고 해서 GHService에서 구현 안 해도 됩니당.(제 부분이지만)
- JavaDocs도 작성했으니 참고 부탁드려요 ~~

Feat: Booking vo 클래스 구현 완료

---

src/com/gh/user/Account.java
src/com/gh/user/Customer.java

Github - https://github.com/JAVA-PJ2/GuestHouse/issues/11
JIRA - GHS-11
###Todo
필드
메소드
toString 오버라이딩
JavaDoc 주석
###ETC

[Feat] Customer, Account 클래스 구현

---

src/com/gh/model/Booking.java
src/com/gh/service/BookingService.java
src/com/gh/service/SearchService.java

Github 이슈 :  #10 
Jira 번호 : GHS-12, GHS-14
###ETC
hasFeature는 인자값 두 개 받는 것으로 변경했습니다 !!

[Feat] GHS-12, 14 BookingService, SearchService 인터페이스 구현

---

src/com/gh/service/GHService.java

Github 이슈 : https://github.com/JAVA-PJ2/GuestHouse/issues/13
Jira 번호 : GHS-13
###ETC

[Feat] GHS-13 GHService 인터페이스 구현

---

.classpath
src/com/gh/service/AnalyticsService.java

Feat:AnalyticsService 인터페이스 구현

---

src/com/gh/model/MusicGH.java
src/com/gh/model/PartyGH.java
src/com/gh/model/PetGH.java

Github 이슈 : https://github.com/JAVA-PJ2/GuestHouse/issues/5
Jira 번호 : GHS-9
###ETC
javadoc 수정했습니다.

[Feat] GHS-9 PartyGH, PetGH, MusicGH 클래스 구현

---

src/com/gh/user/Account.java
src/com/gh/user/Customer.java

Github 이슈 : https://github.com/JAVA-PJ2/GuestHouse/issues/11
Jira 번호 : GHS-11
###ETC
javadoc 수정했습니다.

[Feat] GHS-11 Customer, Account 클래스 구현

---

src/com/gh/model/MusicGH.java
src/com/gh/model/PartyGH.java

[Docs] GHS-9 PartyGH, PetGH, MusicGH 클래스 문서 수정

---

src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

Github 이슈 : #22
Jira 번호 : GHS-22,23,24
ETC
BookingService 클래스에 void deleteBooking(String bookingId);
int -> String으로 수정했습니다.

[Feat] GHS-22 예약(CREATE) 메소드 구현

---

src/com/gh/service/BookingServiceImpl.java

Github - #21 
JIRA - GHS-21
###Todo
###ETC
- bookingId로 예약 정보를 찾았다면 예약 정보를 반환하도록 했습니다.
- 해당 bookingId로 예약 정보를 찾을 수 없습니다. 메시지를 출력 하도록 구현했습니다.
- javadoc 작성했습니다. 참고 부탁드립니다.

[Feat] GHS-21 숙소의 모든 예약 조회(READ) 메소드 구현

---

src/com/gh/model/Booking.java
src/com/gh/model/Guesthouse.java
src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java
src/com/gh/user/Account.java

<h1>이슈번호</h1>
github issue - #27 
jira - GHS-24
<h1>공유 사항</h1>
- Booking.java에 isCancled 필드 추가 + getter, setter도 있음<br/>
- Account 클래스 balance String -> double로 변경<br/>
- Guesthouse클래스 currentPeople 제거 -> dailyPeople 해시맵으로 변경, 날짜 별 인원 추가, 삭제 구현<br/>
- Guesthouse 클래스의 canBook(예약 가능 여부) 임시로 만들었는데 필요하시면 참고하시거나 사용하셔도 됩니다.<br/>
addPeople(체크인날짜, 체크아웃날짜, 인원수) : 이 게하에 이 날짜에 지정 인원수 추가하는 로직<br/>
removePeople(체크인날짜, 체크아웃날짜, 인원수) : 이 게하에 이 날짜에 지정 인원수 제거하는 로직<br/>
이렇게 사용하시면 됩니다 !!<br/><br/>
<h1>Update 구현</h1>
1. 고객이 이 예약을 실제로 가지고 있는지 확인<br/>
2. 예약이 취소되었는지 확인<br/>
3. 시스템 전체 예약 목록에서 해당 예약 찾기<br/>
4. 기존 예약에 대해 환불 처리<br/>
5. 기존 예약 인원을 날짜별로 제거<br/>
6. 새로운 예약이 가능한지 확인<br/>
7. 예약이 가능할 경우 새 요금 계산 및 잔액 검사<br/>
8. 예약이 가능하고 잔액도 충분한 경우: 결제 수행<br/>
9. 날짜별 인원 다시 추가<br/>
10. 예약 정보 시스템에 반영<br/>

Feat: Update 메소드 작성과 vo 클래스 수정

---

src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

Github - #29
JIRA - GHS-20
###Todo
###ETC
- 해당 고객의 예약 정보를 반환하도록 했습니다.
- javadoc 작성했습니다. 참고 부탁드립니다.

[Feat] GHS-20 해당 고객의 모든 예약 조회 메소드 구현

---

src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

Github - #33
JIRA - GHS-19
###Todo
###ETC
- 수용 가능 인원이 full인지 파악해서 true/false 반환
- javadoc 작성했습니다. 참고 부탁드립니다.

[Feat] GHS-19 수용 가능 인원이 full인지 파악 기능

---

src/com/gh/model/Booking.java
src/com/gh/service/BookingServiceImpl.java

관련 이슈
Github - #22
JIRA - #22,#23
###Todo
예약(Create) 메소드 구현
예약 취소(DELETE) 메소드 구현
###ETC
booking
bookingServiceImpl 파일 수정했습니다.

[Feat]GHS-22,23 예약(CREATE) 메소드 구현

---

src/com/gh/app/Main.java
src/com/gh/service/BookingServiceImpl.java

<h1>이슈번호</h1>
github issue - #32  <br/>
jira - GHS-17<br />
<h1>공유사항 - Main 구현</h1>
- Guesthouse 종류와 Customer는 미리 하드코딩으로 만들어놨습니다. <br />
- CRUD 관련 기능은 Scanner로 가능합니다. 테스트 하면서 작성 가능합니다!<br />
- DELETE의 경우 bookingId로 받아오지 말고 Update처럼 리스트를 쫙 뿌려서 번호로 선택해서 삭제하는 방식으로 하면 좋을 것 같습니다(UUID라서 콘솔에 치기 어려움) <br />

Feat: Main에 Switch test code 작성

---

src/com/gh/app/Main.java
src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

우선순위 큐 알고리즘을 적용하여 예약 대기열 알고리즘 구현
1. addBooking에서 수용 가능 인원을 초과했을 경우
enqueueWaitingRequest 메소드를 호출하여 대기열에 넣는 메소드이다.
인자로 예약한 고객 정보(Customer), 예약 정보(Booking), 예약한 현재 시간(LocalDateTime)을 받는다.
우선순위큐를 구현하여 localDateTime.now()를 기준으로 c와 b의 정보를 정렬한다.
addBooking의 !canBook 제어문 안에 이 메소드를 호출하여 대기열에 추가한다.
2. deleteBooking에서 예약을 취소했을 경우
processWaitingList 메소드를 호출하여 대기열의 우선순위가 가장 높은 예약을 자동 예약 처리한다.
빈자리에 따라 대기열에서 예약이 가능하면서 우선순위가 가장 높은 예약을 자동 예약 처리한다.
deleteBooking에서 예약 취소에 성공했을 경우 이 메소드를 호출하고, 대기열에서 예약을 성공했을 경우, addBooking 메소드를 호출하여 예약을 진행한다.
- 추가 구현 사항
예약이 빈 만큼 대기열에서 최대한 넣을 수 있는 만큼 예약 진행하기 ✅
만약 예약이 취소되었는데 대기열에서 예약이 불가능한 경우 대기열에서 예약 가능한 예약이 없다고 메세지 남기기 ✅
addBooking에서 만약 이 게스트 하우스의 최대 수용인원 자체를 넘는 예약이 발생했을 경우 → 예약 인원이 게스트하우스 최대 수용 인원보다 많습니다. 출력 ✅
테스트까지 해봤는데 되더라구요 ^_^
확인 부탁해용...

[Feat] GHS-31#41 예약 대기열 알고리즘 구현

---

src/com/gh/app/Main.java
src/com/gh/model/Guesthouse.java
src/com/gh/service/BookingServiceImpl.java
src/com/gh/service/GuesthouseManager.java

<h1>이슈번호</h1>
github issue - #38  <br/>
jira - GHS-34 <br />
<h1>공유사항 - 가중치 기반 추천 숙소 리스트 반환 구현</h1>
- guesthouse를 비교하여 정렬하는 로직 최대한 수정해서 구현했습니다.

[Docs] GHS-34 기능 수정

---

src/com/gh/app/Main.java
src/com/gh/exception/BookingCancelledException.java
src/com/gh/exception/Exception.java
src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

Feat: delete 예외처리 적용

---

src/com/gh/app/Main.java
src/com/gh/service/GuesthouseManager.java

Description
특정 날짜의 예약률 계산
Todo
예약률 확인 기능 구현
GuesthouseManager 클래스에 calcReservationRate(LocalDate date) 메서드 추가
모든 게스트하우스를 대상으로 특정 날짜의 예약 인원 비율(%) 계산
(해당 날짜 예약 인원 합 / 전체 최대 수용 인원 합) * 100
메인 메뉴(case 7) 확장
사용자가 원하는 날짜를 입력하면 전체 예약률을 확인할 수 있도록 기능 추가
LocalDate.parse()로 날짜 입력 받고 System.out.printf()로 예약률 출력
ETC
너무 어려워요... 확인부탁해요

[Feat] GHS-31#36 특정 날짜의 예약률 계산

---

src/com/gh/model/Guesthouse.java
src/com/gh/service/GuesthouseManager.java

<h1>이슈번호</h1>
github issue - #48  <br/>
jira - GHS-32 <br />
<h1>공유사항 - 특정 게하의 존재 여부 구현</h1>
- 해당 특성이 포함되어있으면 true, 없으면 false로 구현했습니다.

[Feat] GHS-32 특정 게하의 존재 여부 구현

---

src/com/gh/exception/BookingNotFoundException.java

<h1>이슈번호</h1>
github issue - #51  <br/>
jira - GHS-28 <br />
<h1>공유사항 - BookNotFoundException 초기설정</h1>
- 예외 처리 작업 전 초기설정 했습니다.

[Feat] GHS-28 BookNotFoundException 초기설정

---

src/com/gh/app/Main.java
src/com/gh/exception/InsufficientBalanceException.java
src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

잔액 부족 상황에 대해 사용자 정의 예외인 `InsufficientBalanceException`을 적용하고,
`addBooking`, `updateBooking`에 예외 처리를 반영했습니다.
- `InsufficientBalanceException` 생성 및 메시지 커스터마이징 지원
- 예약 시 (`addBooking`) 잔액 부족 시 예외 발생
- 예약 변경 시 (`updateBooking`) 기존 예약 환불 후 잔액 부족이면 복구 처리 + 예외 발생
- `Main` 클래스에서 예외 처리로 사용자에게 안내 메시지 출력
- `deleteBooking`은 기존 `BookingCancelledException`으로 충분하여 변경 없음

GHS-26#30 InsufficientBalanceException 적용

---

src/com/gh/app/Main.java
src/com/gh/exception/BookingCancelledException.java
src/com/gh/model/Guesthouse.java
src/com/gh/service/BookingFileManager.java
src/com/gh/service/BookingServiceImpl.java

#예약 저장 기능 (saveBookingsToCSV)
- GHS-37
- #47 
----------
- 프로그램에서 예약 발생/변경/취소할 때마다 Booking.csv 파일에 저장
- 모든 예약 리스트를 한 번에 덮어쓰기(overwrite)
- 예약 불러오기 기능 (loadBookingsFromCSV)
- Main 시작할 때 실행
- CSV 파싱해서 Booking 객체 생성
- customerName, guesthouseId로 기존 리스트에서 객체 연결
그 후
- Customer.csv나 Guesthouse.csv는 별도로 관리하지 않아도 됨 (중복 저장 없이 매핑으로 연결하면 OK)
booking-홍길동.csv
booking-김철수.csv
이렇게 사람별로 파일을 저장하는 식으로 하기로 !

Feat: 파일 입출력 기능 구현

---

src/com/gh/app/Main.java
src/com/gh/exception/BookingNotFoundException.java
src/com/gh/model/Guesthouse.java
src/com/gh/model/MusicGH.java
src/com/gh/model/PartyGH.java
src/com/gh/service/BookingService.java
src/com/gh/service/BookingServiceImpl.java

Description
BookingNotFoundException적용
☑️ Todo
사용자 정의 예외 클래스 작성
예외 던지는 로직 각 메서드에 적용
인터페이스 throws 선언 정리
Main에 try-catch로 처리
ETC

GHS-26#28 BookingNotFoundException 적용

---

booking-홍길동.csv
src/com/gh/app/Main.java

JIRA - GHS-41
Github issue #57 
- addBooking, updateBooking에 현재 날짜 이전 예약 불가능, 입력 format 오류 시 재 입력 기능

Ghs 41#57 addBooking, updateBooking validation check

---

src/com/gh/app/Main.java

Jira GHS-45
issue - #60 
- 람다식 forEach로 리팩토링 
- 현업에서 `AtomicInteger `많이 사용한다고 해서 사용해보았음

Refactor: Change updateBooking test code to lambda format

---

src/com/gh/app/Main.java
src/com/gh/service/BookingServiceImpl.java

jira : GHS-44
issue : #63 
-[ ] 디버깅용, 추후 대기열 리스트 출력 가능 toString을 Optinal, null-safe 리팩토링
-[ ] 우선순위 대기열에서 자동예약 처리 메소드의 while을 removeIf(람다식)으로 리팩토링
두 번째 processWaitingList에서 while문을 쓰는 이유는 현재 대기열에서 자동예약이 가능한 모든 예약을 자동예약처리해주는데, Stream, filter, findfirst를 사용하면 1개만 추가가 되어서 
한 번에 처리하는 이 방식이 아닌, removeIf 구조를 사용하여 구현했습니다.
removeIf : Collection 람다 기반 필터링 제거 함수로, 조건이 true를 반환하면 해당 요소는 리스트에서 제거된다.

[Refactor] GHS-44#63 예약 대기열 우선순위 큐 람다식으로 리팩토링

---

src/com/gh/app/Main.java

Jira GHS-51
issue - #66
- 예약 취소 시 목록 출력 AtomicInteger로 리팩토링했습니다.

[Refactor] GHS-51 예약 취소 시 목록 출력 AtomicInteger로 리팩토링

---

src/com/gh/app/Main.java

jira : GHS-43
issue : #69
Todo
- 게스트하우스 목록 출력에 IntStream.range 사용하여 반복문 간결화
- 선택한 게스트하우스 조회 시 Optional 사용으로 null 처리 강화
- 시작 날짜 입력 시 Optional.filter와 예외처리로 날짜 유효성 검증 개선
etc

Refactor: 예약 가능한 게스트하우스 선택 및 날짜 입력 부분에 Stream과 Optional 적용
